const express = require('express');
const router = express.Router();
const schoolController = require('../controller/schoolController');
router.get('/school',schoolController.registeredSchool);
router.post('/add_school',schoolController.postSchool);
router.delete('/delete_student/:id',schoolController.DeleteSchool);
// router.get('/specific_student/:id',studentController.getDetails);
// router.post('/add_student',studentController.createStudent);
// router.post('/update_student/:id',studentController.updateStudent);
// router.patch('/patch_student/:id',studentController.patchStudent);
module.exports = router;